traefik:
  image: traefik:v2.9.6
  logLevel: "DEBUG"
  domain: "virtual33.myguest.virtualbox.org"
  exposedByDefault: false

ports:
  http: 80
  https: 443
  sshNetconf: 4334
  tlsNetconf: 4335


resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"

