apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-middleware
data:
  middleware.yaml: |
    http:
      middlewares:
        strip:
          stripPrefix:
            prefixes:
              - "/traefik"
        default-headers:  
          headers:
            CustomFrameOptionsValue: "SAMEORIGIN"
            sslRedirect: true
            browserXssFilter: true
            contentTypeNosniff: true
            forceSTSHeader: true
            stsSeconds: 315360000
            stsIncludeSubdomains: true
            stsPreload: true
