apiVersion: v1
kind: Service
metadata:
  name: traefik
spec:
  type: NodePort
  ports:
    - name: web
      port: 80
      targetPort: web
      nodePort: 30080
    - name: websecure
      port: 443
      targetPort: websecure
      nodePort: 30443
    - name: dashboard
      port: 8080
      targetPort: dashboard
      nodePort: 28932
  selector:
    app: traefik

